export var items1 = [
  'Boots of Speed',
  'Faerie Charm',
  'Rejuvenation Bead',
  "Giant's Belt",
  'Cloak of Agility',
  'Blasting Wand',
  'Sapphire Crystal',
  'Ruby Crystal',
  'Cloth Armor',
  'Chain Vest',
  'Null-Magic Mantle',
  'Long Sword',
  'Pickaxe',
  'B. F. Sword',
  "Hunter's Talisman",
  "Hunter's Machete",
  'Dagger',
  'Recurve Bow',
  'Amplifying Tome',
  'Vampiric Scepter',
  "Doran's Shield",
  "Doran's Blade",
  "Doran's Ring",
  'Negatron Cloak',
  'Needlessly Large Rod',
  'Dark Seal',
  'Cull',
  'Health Potion',
  'Showdown Health Potion',
  'Total Biscuit of Rejuvenation',
  'Kircheis Shard',
  'Refillable Potion',
  'Corrupting Potion',
  "Oracle's Extract",
  "Guardian's Horn",
  'Poro-Snax',
  'Diet Poro-Snax',
  'Control Ward',
  "Shurelya's Reverie",
  'Elixir of Iron',
  'Elixir of Sorcery',
  'Elixir of Wrath',
  'Commencing Stopwatch',
  'Stopwatch',
  'Slightly Magical Boots',
  'Perfectly Timed Stopwatch',
  'Abyssal Mask',
  "Archangel's Staff",
  'Manamune',
  "Berserker's Greaves",
  "Archangel's Staff (Quick Charge)",
  'Manamune (Quick Charge)',
  'Boots of Swiftness',
  'Catalyst of Aeons',
  "Sorcerer's Shoes",
  'Frozen Mallet',
  'Glacial Shroud',
  'Iceborn Gauntlet',
  'Guardian Angel',
  'Rod of Ages',
  'Chalice of Harmony',
  'Rod of Ages (Quick Charge)',
  'Hextech GLP-800',
  'Infinity Edge',
  'Mortal Reminder',
  'Last Whisper',
  "Lord Dominik's Regards",
  "Seraph's Embrace",
  "Mejai's Soulstealer",
  'Muramana',
  'Muramana',
  'Phage',
  'Phantom Dancer',
  'Ninja Tabi',
  "Seraph's Embrace",
  "Zeke's Convergence",
  "Jaurim's Fist",
  "Sterak's Gage",
  'Sheen',
  'Spirit Visage',
  'Kindlegem',
  'Sunfire Cape',
  'Tear of the Goddess',
  'Black Cleaver',
  'Bloodthirster',
  'Tear of the Goddess (Quick Charge)',
  'Ravenous Hydra',
  'Thornmail',
  'Bramble Vest',
  'Tiamat',
  'Trinity Force',
  "Warden's Mail",
  "Warmog's Armor",
  "Runaan's Hurricane",
  'Zeal',
  'Statikk Shiv',
  "Rabadon's Deathcap",
  "Wit's End",
  'Rapid Firecannon',
  'Stormrazor',
'Lich Bane',
  'Stinger',
  "Banshee's Veil",
  'Aegis of the Legion',
  'Redemption',
  'Fiendish Codex',
  "Knight's Vow",
  'Frozen Heart',
  "Mercury's Treads",
  "Guardian's Orb",
  'Aether Wisp',
  'Forbidden Idol',
  "Nashor's Tooth",
  "Rylai's Crystal Scepter",
  'Boots of Mobility',
  "Executioner's Calling",
  "Guinsoo's Rageblade",
  "Caulfield's Warhammer",
  'Serrated Dirk',
  'Void Staff',
  'Haunting Guise',
  'Mercurial Scimitar',
  'Quicksilver Sash',
  "Youmuu's Ghostblade",
  "Randuin's Omen",
  'Bilgewater Cutlass',
  'Hextech Revolver',
  'Hextech Gunblade',
  'Duskblade of Draktharr',
  "Liandry's Torment",
  'Hextech Protobelt-01',
  'Blade of the Ruined King',
  'Hexdrinker',
  'Maw of Malmortius',
  "Zhonya's Hourglass",
  'Ionian Boots of Lucidity',
  'Morellonomicon',
  "Athene's Unholy Grail",
  'Umbral Glaive',
  'Sanguine Blade',
  "Guardian's Hammer",
  'Locket of the Iron Solari',
  "Seeker's Armguard",
  'Gargoyle Stoneplate',
  'Adaptive Helm',
  'Hex Core mk-1',
  'Hex Core mk-2',
  'Perfect Hex Core',
  'Prototype Hex Core',
  "Spectre's Cowl",
  "Mikael's Crucible",
  "Luden's Echo",
  'Scarecrow Effigy (Trinket)',
  'Warding Totem (Trinket)',
  'Greater Stealth Totem (Trinket)',
  'Greater Vision Totem (Trinket)',
  'Farsight Alteration',
  'Oracle Lens',
  'Molten Edge',
  'Forgefire Cape',
  "Rabadon's Deathcrown",
  'Infernal Mask',
  'Obsidian Cleaver',
  'Salvation',
  'Circlet of the Iron Solari',
  'Trinity Fusion',
  "Zhonya's Paradox",
  'Frozen Fist',
  "Youmuu's Wraithblade",
  'Might of the Ruined King',
  "Luden's Pulse",
  'Ardent Censer',
  'Essence Reaver',
  'Black Spear',
  'Black Spear',
  'Frosted Snax',
  'Super Spicy Snax',
  'Espresso Snax',
  'Rainbow Snax Party Pack!',
  'Dawnbringer Snax',
  'Nightbringer Snax',
  "Stalker's Blade",
  "Skirmisher's Sabre",
  "Dead Man's Plate",
  'Titanic Hydra',
  "Bami's Cinder",
  'Righteous Glory',
  'Crystalline Bracer',
  'Lost Chapter',
  "Death's Dance",
  'Edge of Night',
  "Spellthief's Edge",
  'Frostfang',
  'Shard of True Ice',
  'Steel Shoulderguards',
  'Runesteel Spaulders',
  'Pauldrons of Whiterock',
  'Relic Shield',
  "Targon's Buckler",
  'Bulwark of the Mountain',
  'Spectral Sickle',
  'Harrowing Crescent',
  'Black Mist Scythe',
  'Fire at Will',
  "Death's Daughter",
  'Raise Morale',
  'Twin Shadows',
  'Spellbinder',
  'Oblivion Orb'
]